### ISSUE TITLE
下载这么多居然没人star

### ISSUE THREAD

**Issue by yangmeishu** [Saturnluohao/BackgroundImageFromBing#1]
一直有自动下载bing壁纸到电脑背景，今天突然想着自动到ide的想法会不会看着美景思维就会更敏捷活跃。想着可能要自己写插件。一搜索居然有了。看了作者邮箱又是中国的，特意来这里star。

**Comment by yangmeishu** [comment]
希望增加一个透明度的设置

**Comment by Saturnoul** [comment]
哈哈，我本人也是很喜欢Bing的每日图片，我的电脑桌面和IDE背景都喜欢设置成Bing的每日推送图片。这个Jetbrains插件是我参照以前的背景插件修改来的，用来自己娱乐，没想到也有同志有相同的爱好。这两天在学车比较忙，收到你的邮件后我临时在设置里加了一个透明度设置，现在提交需要等待Jetbrains审核，预计明天可以通过，非常感谢你的反馈!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Saturnluohao/BackgroundImageFromBing"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月6日(星期五) 上午8:42
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [Saturnluohao/BackgroundImageFromBing] 下载这么多居然没人star (#1)





 
希望增加一个透明度的设置
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
